name: smart_farming
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # gauge: ^0.3.2
  path_provider: ^2.1.2
  mqtt_client: ^10.0.0
  http: ^0.13.0
  fl_chart: ^0.55.2
  syncfusion_flutter_gauges: ^29.2.5
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/
